server:
  port: 8089
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:80
          predicates:
            - Path=/api/**
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka