server:
  port: 8089
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/api/**

        - id: discovery
          uri: http://discovery:8761
          predicates:
              - Path=/**
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka